name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest

      # Add this step to send failure notification to Mattermost
      - name: Send failure notification to Mattermost
        if: failure()  # This ensures it only runs if a previous step failed
        uses: tferreira/mattermost-action@master
        with:
          webhook-url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          #channel: 'builds-channel'  # Optional: specify channel
          #username: 'GitHub Actions'  # Optional: override username
          #icon-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'  # Optional
          text: |
            :x: **Build Failed!**
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            [See Action Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})