name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest

      - name: Send success notification to Mattermost
        if: success()  # This ensures it only runs if all previous steps succeeded
        uses: appleboy/mattermost-action@master
        with:
          webhook_url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          message: |
            :white_check_mark: **Build Succeeded!**
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            [See Action Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Send failure notification to Mattermost
        if: failure()  # This ensures it only runs if a previous step failed
        uses: appleboy/mattermost-action@master
        with:
          webhook_url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          message: |
            :x: **Build Failed!**
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            [See Action Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})